{{- define "service" -}}
{{- $root:= . }}
{{- range $service := .Values.services}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" $root }}-svc-{{ $service.name }}
{{- if $service.annotations }}
  annotations:
{{- range $key, $value := $service.annotations }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "microservice.fullname" $root }}-svc-{{ $service.name }}
    helm.sh/chart: {{ include "microservice.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  type: {{  $service.type }}
  selector:
    app.kubernetes.io/name: {{ include "microservice.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
  ports:
    {{- range $spec := $service.specs }}
    - name: {{ $spec.name }}
      port: {{ $spec.port }}
      protocol: {{ $spec.protocol | default "TCP" }}
            {{- if $spec.targetPort }}
      targetPort: {{ $spec.targetPort }}
            {{- end}}
        {{- if  $spec.nodePort }}
      nodePort: {{  $spec.nodePort }}
          {{- end }}
     {{- end -}}
{{- end -}}
{{- end -}}