on: [push, pull_request]
name: Test
jobs:
  test: 
    runs-on: [ubuntu-latest]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0
    - name: Install Helm
      run: |
        curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v .
      working-directory: ./test